### PR TITLE
fix: bumps to AzureRM 4, deps updates

### PR DESCRIPTION
**Pull request by ElvenSpellmaker**
#### 📲 What

 - Bumps AzureRM to 4
 - Include lockfile
 - Bumps other deps
 - Moves var and output to correct files

#### 🤔 Why

New stacks-terraform app needs v4, and security updates

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [ ] Rebased/merged with latest changes from development and re-tested?
- [ ] Meeting the Coding Standards?

### CODE REVIEW

**Comment by ElvenSpellmaker** [comment]
This isn't an us problem... https://github.com/jeremylong/DependencyCheck/issues/7067

**Review by Athy17 — APPROVED** [review]

**Pull request merged**
